### ISSUE TITLE
Menu hide fix causing first menu item to automatically when menu button activated

### ISSUE THREAD

**Issue by mark-101** [chrisdivyak/EasyAsPie#8]
Hi Chris,
First, thanks for a very useful bit of code.
We have been playing with EasyAsPie with a view to using it on our site but have found some odd behaviour on mobile devices (less than 800px wide).   We get the same behaviour on your demo site.

If the top level of the menu is displayed (the menubtn has been clicked/touched) the bit of code following line 93 in easyaspie.js causes the first UL to open automatically which isn't the behaviour we were expecting.  It will consistently do this if you change the orientation of the device while the top level menu is displayed but on some devices (Firefox on Android 5.0.1 and the Android browser on Android 2.3.5) it does it immediately the menubtn is activated.

I have "fixed" this on my local copy by commenting out lines 93-96 but I am pretty sure this isn't the right solution.  I can't replicate the menu hide issue that caused you to add the fix in the first place which doesn't give me confidence that I haven't reintroduced the original problem.

I hope this makes sense to you and that you can replicate our issue.

Thanks
Mark

**Comment by chrisdivyak** [comment]
I haven't checked this branch in awhile so sorry for the delay. I fixed the js file with an update to the issue you are experiencing. it should close the menu always on resize now.
