### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Lucati** [chrisdivyak/EasyAsPie#9]
I've tried to make your menu to work but i can't it seems to have a problem in this part of the js

(jQuery)(function ($) {
$.fn.extend({
easyPie: function (options) {

http://codepen.io/Lucati/pen/gbxpYZ

**Comment by chrisdivyak** [comment]
I did a jsfiddle instead so I could pull in jquery. This menu works so just update your code and it should be good to go. 

http://jsfiddle.net/mydkj84x/

**Comment by Lucati** [comment]
Thank you, i made my on version on a local machine website and worked to, sadly im working with a platform that generate his on code messing code an consequent your menu.
